# FIXME: https://github.com/bbatsov/rubocop/pull/1871
Performance/Sample:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Not:
  Enabled: false

Style/TrailingComma:
  EnforcedStyleForMultiline: comma
