DuplicateMethodCall:
  exclude:
  - Signore::Database#find

FeatureEnvy:
  exclude:
    - Signore::Executable::Settings#forbidden

IrresponsibleModule:
  enabled: false

NestedIterators:
  exclude:
  - Signore::Database#find
  max_allowed_nesting: 2

UnusedParameters:
  enabled: false
