DuplicateMethodCall:
  exclude:
    - Signore::SigFinder#find_tagged

FeatureEnvy:
  exclude:
    - Signore::Settings#forbidden

IrresponsibleModule:
  enabled: false

NestedIterators:
  max_allowed_nesting: 2
